version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Shota0925
      MYSQL_DATABASE: sample
      MYSQL_USER: ShotaKikuchi
      MYSQL_PASSWORD: Shota0925
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - default
  app:
    image: node:12
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm start
    networks:
      - default
    depends_on:
      - mysql
networks:
  default:
volumes:
  mysqldata:
